@startuml

title ER диаграмма

entity  User {
    * id : UUID
    --
    name : String
    email : String
    password : String
}

entity  House {
    * id : UUID
    --
    user_id: UUID
    name: String
    location: String
    devices: Device[]
    serial_number: Number

}

entity  Device {
    * id : UUID
    --
    name: String
    status: String
    house_id: UUID
    type_id: UUID
}

entity  DeviceType {
    * id : UUID
    --
    name: String
}

entity  Module {
    * id : UUID
    --

}

entity  TelemetryData {
    * id : UUID
    --

}

User ||--o{ House
House ||--o{ Device

@enduml